grpcServer: 
  host: "localhost"
  port: 5002
  timeoutInMilSec: 500
httpServer:
  host: "localhost"
  port: 5003
  timeoutInMilSec: 500
subClient:
  host: "localhost"
  port: 5001
unreadCntClient:
  host: "localhost"
  port: 5001
notifClient:
  url: "http//:boturl.com/"